<?php
/**
 * MagePal Google Tag Manager for Magento 1
 *
 * Copyright © 2016 MagePal. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $this MagePal_GoogleTagManager_Block_Tm **/ ?>
<?php $accountId = $this->getAccountId(); ?>

<noscript><iframe src="//www.googletagmanager.com/ns.html?id=<?php echo $accountId ?>"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
